### PR TITLE
Fix connector value layer

### PR DESCRIPTION
**Pull request by rnestler**
Based on #3

### CODE REVIEW

**Comment by rnestler** [comment]
Honestly I don't understand the purpose of the different layers in the schematics editor, but well :wink:

**Comment by dbrgn** [comment]
@rnestler since #3 was closed without merging, can you rebase onto master?

(By the way, why is this even based on the commit in #3? It looks like the changes are completely independent... You're only modifying symbols, not components.)

**Comment by dbrgn** [comment]
@ubruhin I guess I can merge this, since it's a trivial change (and has been open for review for 4 months).

**Comment by ubruhin** [comment]
> I guess I can merge this, since it's a trivial change (and has been open for review for 4 months).

...and was not finished yet for 4 months :wink:

But the changes are good of course.

**Comment by dbrgn** [comment]
It couldn't be merged because of the pending rebase, but the change was finished and labelled as `ready for review` :wink: I regularly go through all issues labelled with that label to keep them up to date for you. https://github.com/issues?q=is%3Aopen+is%3Apr+org%3Alibrepcb-libraries+archived%3Afalse+label%3A%22ready+for+review%22

**Pull request merged**
